### ISSUE TITLE
Convert all 1D time stamps to delta time

### ISSUE THREAD

**Issue by sinanshi** [UCL-HIC/ccanonym#7]
- [x] convert all 1D date time to delta time.
- [x] remove admission time longer than threshold.

**Comment by sinanshi** [comment]
@docsteveharris I would like to have the ccanonym package submitted to the reviewers today. Do you think we should add this feature? This idea was not presented the SOP document you sent last week. I don't know if that will be a problem for you to explain or not.

**Comment by docsteveharris** [comment]
If possible, I think this should be in the package.

If it's a major delay, then we can re-think.

S

**Comment by sinanshi** [comment]
I guess it won't be a major delay. I will do my best.
